import { type Task, TaskStatus } from "./types"

export const mockTasks: Task[] = [
  {
    id: 1,
    title: "프로젝트 기획서 작성",
    description: "프로젝트 범위, 일정, 리소스 계획 포함",
    status: TaskStatus.DONE,
    tags: "기획,문서",
    priority: 1,
    dueDate: "2025-05-15",
    estimatedTimeHours: 4,
    actualTimeHours: 5.5,
    subTasks: [
      {
        id: 8,
        title: "요구사항 분석",
        description: "사용자 요구사항 수집 및 분석",
        status: TaskStatus.DONE,
        tags: "기획,분석",
        priority: 2,
        dueDate: "2025-05-10",
        estimatedTimeHours: 2,
        actualTimeHours: 2.5,
        subTasks: [],
      },
      {
        id: 9,
        title: "일정 계획 수립",
        description: "마일스톤 및 세부 일정 계획",
        status: TaskStatus.DONE,
        tags: "기획,일정",
        priority: 2,
        dueDate: "2025-05-12",
        estimatedTimeHours: 1.5,
        actualTimeHours: 2,
        subTasks: [],
      },
    ],
  },
  {
    id: 2,
    title: "디자인 시스템 구축",
    description: "컴포넌트 라이브러리 및 스타일 가이드 작성",
    status: TaskStatus.DOING,
    tags: "디자인,프론트엔드",
    priority: 2,
    dueDate: "2025-05-25",
    estimatedTimeHours: 12,
    actualTimeHours: 8,
    subTasks: [
      {
        id: 10,
        title: "색상 팔레트 정의",
        description: "브랜드 색상 및 UI 색상 정의",
        status: TaskStatus.DONE,
        tags: "디자인",
        priority: 3,
        dueDate: "2025-05-20",
        estimatedTimeHours: 2,
        actualTimeHours: 1.5,
        subTasks: [],
      },
      {
        id: 11,
        title: "타이포그래피 설정",
        description: "폰트 패밀리 및 크기 정의",
        status: TaskStatus.DOING,
        tags: "디자인",
        priority: 3,
        dueDate: "2025-05-22",
        estimatedTimeHours: 1,
        subTasks: [],
      },
      {
        id: 12,
        title: "컴포넌트 디자인",
        description: "버튼, 입력 필드 등 기본 컴포넌트 디자인",
        status: TaskStatus.DOING,
        tags: "디자인,UI",
        priority: 2,
        dueDate: "2025-05-24",
        estimatedTimeHours: 4,
        subTasks: [],
      },
    ],
  },
  {
    id: 3,
    title: "API 엔드포인트 설계",
    description: "RESTful API 구조 및 문서화",
    status: TaskStatus.TODO,
    tags: "백엔드,API",
    priority: 2,
    dueDate: "2025-05-30",
    estimatedTimeHours: 6,
    subTasks: [],
  },
  {
    id: 4,
    title: "사용자 인증 구현",
    description: "로그인, 회원가입, 비밀번호 재설정 기능",
    status: TaskStatus.DOING,
    tags: "백엔드,보안",
    priority: 1,
    dueDate: "2025-05-22",
    estimatedTimeHours: 8,
    subTasks: [
      {
        id: 13,
        title: "로그인 API 구현",
        description: "JWT 토큰 기반 인증",
        status: TaskStatus.DOING,
        tags: "백엔드,보안,API",
        priority: 1,
        dueDate: "2025-05-20",
        estimatedTimeHours: 3,
        subTasks: [],
      },
      {
        id: 14,
        title: "회원가입 기능 구현",
        description: "이메일 인증 포함",
        status: TaskStatus.TODO,
        tags: "백엔드,보안",
        priority: 2,
        dueDate: "2025-05-21",
        estimatedTimeHours: 2,
        subTasks: [],
      },
    ],
  },
  {
    id: 5,
    title: "대시보드 UI 개발",
    description: "사용자 대시보드 화면 구현",
    status: TaskStatus.TODO,
    tags: "프론트엔드,UI",
    priority: 3,
    dueDate: "2025-06-05",
    estimatedTimeHours: 10,
    subTasks: [],
  },
  {
    id: 6,
    title: "데이터베이스 스키마 설계",
    description: "엔티티 관계 모델링 및 인덱싱 전략",
    status: TaskStatus.DONE,
    tags: "백엔드,데이터베이스",
    priority: 2,
    dueDate: "2025-05-10",
    estimatedTimeHours: 5,
    actualTimeHours: 4,
    subTasks: [],
  },
  {
    id: 7,
    title: "성능 최적화",
    description: "페이지 로딩 속도 및 렌더링 성능 개선",
    status: TaskStatus.TODO,
    tags: "프론트엔드,성능",
    priority: 4,
    dueDate: "2025-06-15",
    estimatedTimeHours: 8,
    subTasks: [],
  },
]
